/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.invoicesystem.forms;

import sk.upjs.invoicesystem.*;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GradientPaint;
import java.util.List;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.Plot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.StandardBarPainter;
import org.jfree.data.xy.IntervalXYDataset;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author martinapivarnikova
 */
public class ChartDialog extends javax.swing.JDialog {

    StatisticsDao statisticsDao;

    /**
     * Creates new form ChartDialog
     */
    public ChartDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        statisticsDao = ObjectFactory.INSTANCE.getStatisticsDao();
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chartJPanel = new javax.swing.JPanel();
        createChartButton = new javax.swing.JToggleButton();
        companyComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(504, 517));
        setMinimumSize(new java.awt.Dimension(504, 517));
        setPreferredSize(new java.awt.Dimension(504, 517));
        getContentPane().setLayout(null);

        chartJPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout chartJPanelLayout = new javax.swing.GroupLayout(chartJPanel);
        chartJPanel.setLayout(chartJPanelLayout);
        chartJPanelLayout.setHorizontalGroup(
            chartJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );
        chartJPanelLayout.setVerticalGroup(
            chartJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        getContentPane().add(chartJPanel);
        chartJPanel.setBounds(10, 150, 483, 299);

        createChartButton.setFont(new java.awt.Font("Alegreya", 3, 13)); // NOI18N
        createChartButton.setForeground(new java.awt.Color(0, 51, 153));
        createChartButton.setText("Create chart");
        createChartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createChartButtonActionPerformed(evt);
            }
        });
        getContentPane().add(createChartButton);
        createChartButton.setBounds(320, 110, 160, 31);

        companyComboBox.setModel(new CompanyComboBoxModel());
        getContentPane().add(companyComboBox);
        companyComboBox.setBounds(10, 110, 306, 27);

        jLabel4.setFont(new java.awt.Font("Nickainley", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Chart");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 10, 100, 60);

        jLabel6.setFont(new java.awt.Font("Alegreya", 2, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Choose company");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 76, 140, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/martinapivarnikova/Downloads/Large_UL-877.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-10, 0, 530, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createChartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createChartButtonActionPerformed
        XYSeries Statistics = new XYSeries("");
        Company company = (Company) companyComboBox.getSelectedItem();

        for (int i = 0; i < 12; i++) {
            try {
                Statistics.add(i, statisticsDao.calculateEarnings(company.getId(), i));
            } catch (NullPointerException e) {
                Statistics.add(i, 0);
            }

        }
        XYDataset xyDataset = new XYSeriesCollection(Statistics);
        JFreeChart jFreeChart = ChartFactory.createXYBarChart("", "", false, "", (IntervalXYDataset) xyDataset, PlotOrientation.VERTICAL, false, false, false);
        jFreeChart.setBackgroundPaint(Color.WHITE);

        XYPlot plot = (XYPlot) jFreeChart.getPlot();
        for (int i = 0; i < 12; i++) {
             plot.getRenderer().setSeriesPaint(i, new Color(0,51,153));
        }
       
        
        ChartPanel chartPanel = new ChartPanel(jFreeChart);
        chartJPanel.removeAll();
        chartJPanel.setLayout(new java.awt.BorderLayout());
        chartJPanel.add(chartPanel, BorderLayout.CENTER);
        chartJPanel.validate();
    }//GEN-LAST:event_createChartButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChartDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChartDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChartDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChartDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChartDialog dialog = new ChartDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chartJPanel;
    private javax.swing.JComboBox<Company> companyComboBox;
    private javax.swing.JToggleButton createChartButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
