/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.invoicesystem.forms;

import sk.upjs.invoicesystem.*;

/**
 *
 * @author kriza
 */
public class ChooseCompanyForm extends javax.swing.JDialog {

    private CreateInvoiceForm createInvoiceForm;
    private String selectedCompany;

    /**
     * Creates new form ChooseCompanyForm
     */
    public ChooseCompanyForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        setLocationRelativeTo(parent);
    }

    public ChooseCompanyForm(javax.swing.JDialog parent, boolean modal, String company) {
        super(parent, modal);
        initComponents();
        createInvoiceForm = (CreateInvoiceForm) parent;
        selectedCompany = company;
        refreshCompaniesForm();
    }

    private void refreshCompaniesForm() {
        CompaniesTableModel model = (CompaniesTableModel) companiesTable.getModel();
        model.refresh(searchField.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        companiesTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Choose company");
        setMaximumSize(new java.awt.Dimension(441, 429));
        setMinimumSize(new java.awt.Dimension(441, 429));
        setPreferredSize(new java.awt.Dimension(441, 429));
        getContentPane().setLayout(null);

        selectButton.setFont(new java.awt.Font("Alegreya", 3, 13)); // NOI18N
        selectButton.setForeground(new java.awt.Color(0, 51, 153));
        selectButton.setText("Select");
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });
        getContentPane().add(selectButton);
        selectButton.setBounds(310, 370, 120, 29);

        searchButton.setFont(new java.awt.Font("Alegreya", 3, 13)); // NOI18N
        searchButton.setForeground(new java.awt.Color(0, 51, 153));
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton);
        searchButton.setBounds(300, 70, 130, 29);
        getContentPane().add(searchField);
        searchField.setBounds(10, 70, 290, 30);

        companiesTable.setModel(new CompaniesTableModel());
        jScrollPane2.setViewportView(companiesTable);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 110, 410, 250);

        jLabel2.setFont(new java.awt.Font("Nickainley", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Choose company");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 10, 230, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/martinapivarnikova/Downloads/Large_UL-877.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 470, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        int selectedRow = companiesTable.getSelectedRow();
        if (selectedRow != -1) {
           Company company = (Company) ((CompaniesTableModel) companiesTable.getModel()).getObjectAt(selectedRow);
           if (selectedCompany.equals("supplier")) {
                createInvoiceForm.setSupplier(company);
                createInvoiceForm.setButtonTextChooseSupplier(company.getCompanyName());
            } else {
                createInvoiceForm.setCustomer(company);
                createInvoiceForm.setButtonTextChooseCustomer(company.getCompanyName());
            }

            dispose();
        }

    }//GEN-LAST:event_selectButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed

        refreshCompaniesForm();
    }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseCompanyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseCompanyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseCompanyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseCompanyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new ChooseCompanyForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable companiesTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton selectButton;
    // End of variables declaration//GEN-END:variables
}
