/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.invoicesystem.forms;

import sk.upjs.invoicesystem.CompaniesDao;
import sk.upjs.invoicesystem.CompaniesTableModel;
import sk.upjs.invoicesystem.Company;
import sk.upjs.invoicesystem.ObjectFactory;

/**
 *
 * @author kriza
 */
public class CompaniesForm extends javax.swing.JDialog {
    
    CompaniesDao companies = ObjectFactory.INSTANCE.getCompanyDao();
    
    String lastSearch;

    /**
     * Creates new form CompaniesForm
     */
    public CompaniesForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        setLocationRelativeTo(parent);
        refreshCompaniesForm();
    }
    
    private void refreshCompaniesForm() {
        CompaniesTableModel model = (CompaniesTableModel) companiesTable.getModel();
        lastSearch = searchField.getText();
        model.refresh(lastSearch);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteCompanyButton = new javax.swing.JButton();
        createCompanyButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        companiesTable = new javax.swing.JTable();
        updateCompanyButton = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Companies");
        setBounds(new java.awt.Rectangle(0, 0, 550, 610));
        setMaximumSize(new java.awt.Dimension(550, 610));
        setMinimumSize(new java.awt.Dimension(550, 610));
        setPreferredSize(new java.awt.Dimension(550, 610));
        getContentPane().setLayout(null);

        deleteCompanyButton.setFont(new java.awt.Font("Alegreya", 3, 18)); // NOI18N
        deleteCompanyButton.setForeground(new java.awt.Color(0, 51, 153));
        deleteCompanyButton.setText("Delete company");
        deleteCompanyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCompanyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteCompanyButton);
        deleteCompanyButton.setBounds(180, 90, 149, 40);

        createCompanyButton.setFont(new java.awt.Font("Alegreya", 3, 18)); // NOI18N
        createCompanyButton.setForeground(new java.awt.Color(0, 51, 153));
        createCompanyButton.setText("Create company");
        createCompanyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCompanyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(createCompanyButton);
        createCompanyButton.setBounds(370, 90, 149, 40);

        companiesTable.setModel(new CompaniesTableModel());
        jScrollPane1.setViewportView(companiesTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 190, 510, 360);

        updateCompanyButton.setFont(new java.awt.Font("Alegreya", 3, 18)); // NOI18N
        updateCompanyButton.setForeground(new java.awt.Color(0, 51, 153));
        updateCompanyButton.setText("Update company");
        updateCompanyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCompanyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateCompanyButton);
        updateCompanyButton.setBounds(20, 90, 149, 40);
        getContentPane().add(searchField);
        searchField.setBounds(20, 140, 400, 40);

        searchButton.setFont(new java.awt.Font("Alegreya", 3, 18)); // NOI18N
        searchButton.setForeground(new java.awt.Color(0, 51, 153));
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton);
        searchButton.setBounds(420, 140, 106, 40);

        jLabel1.setFont(new java.awt.Font("Nickainley", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Companies");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 10, 200, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/martinapivarnikova/Downloads/Large_UL-877.jpg")); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(550, 610));
        jLabel2.setMinimumSize(new java.awt.Dimension(550, 610));
        jLabel2.setPreferredSize(new java.awt.Dimension(550, 610));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 550, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void createCompanyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCompanyButtonActionPerformed
        CreateCompanyForm createCompanyForm = new CreateCompanyForm(this, true);
        createCompanyForm.setVisible(true);
        refreshCompaniesForm();

    }//GEN-LAST:event_createCompanyButtonActionPerformed

    private void deleteCompanyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCompanyButtonActionPerformed
        int selectedRow = companiesTable.getSelectedRow();
        if (selectedRow != -1) {
            Company selected = companies.searchCompaniesByName(lastSearch).get(selectedRow);
            companies.deleteCompany(selected);
            refreshCompaniesForm();
        }

    }//GEN-LAST:event_deleteCompanyButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        refreshCompaniesForm();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void updateCompanyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCompanyButtonActionPerformed
        int selectedRow = companiesTable.getSelectedRow();
        if (selectedRow != -1) {
            CreateCompanyForm updatingCompany = new CreateCompanyForm(this, true, selectedRow);
            updatingCompany.setVisible(true);
            refreshCompaniesForm();
        }
    }//GEN-LAST:event_updateCompanyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompaniesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompaniesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompaniesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompaniesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new CompaniesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable companiesTable;
    private javax.swing.JButton createCompanyButton;
    private javax.swing.JButton deleteCompanyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton updateCompanyButton;
    // End of variables declaration//GEN-END:variables
}
