package sk.upjs.invoicesystem.forms;

import java.awt.Color;
import sk.upjs.invoicesystem.CompaniesDao;
import sk.upjs.invoicesystem.ObjectFactory;
import sk.upjs.invoicesystem.Company;

/**
 *
 * @author kriza
 */
public class CreateCompanyForm extends javax.swing.JDialog {

    private CreateInvoiceForm createInvoiceForm;
    private CompaniesDao companies = ObjectFactory.INSTANCE.getCompanyDao();
    private Company selected = null;
    private String whoIsCreating = null;

    /**
     * Creates new form CreateInvoiceForm
     */
    public CreateCompanyForm(javax.swing.JDialog parent, boolean modal, int selectedRow) {
        super(parent, modal);
        
        initComponents();
        setLocationRelativeTo(parent);

        selected = companies.getCompanies().get(selectedRow);

        companyNameField.setText(selected.getCompanyName());
        streetField.setText(selected.getStreet());
        cityField.setText(selected.getCity());
        if (selected.getPostalCode() != null) {
            ZIPField.setText(Integer.toString(selected.getPostalCode()));
        }
        countryField.setText(selected.getCountry());
        if (selected.getICO() != null) {
            ICOField.setText(Long.toString(selected.getICO()));
        }
        if (selected.getDIC() != null) {
            DICField.setText(Long.toString(selected.getDIC()));
        }
        if (selected.getICDPH() != null) {
            DPHField.setText(Long.toString(selected.getICDPH()));
        }
        telephoneNumberField.setText(selected.getTelephoneNumber());
        emailField.setText(selected.getEmail());
        IBANField.setText(selected.getIBAN());
        createCompanyButton.setText("Update");
    }

    public CreateCompanyForm(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    public CreateCompanyForm(javax.swing.JDialog parent, boolean modal, String whoIsCreating) {
        super(parent, modal);
        initComponents();
        this.whoIsCreating = whoIsCreating;
        createInvoiceForm = (CreateInvoiceForm) parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        companyNameField = new javax.swing.JTextField();
        ZIPField = new javax.swing.JTextField();
        streetField = new javax.swing.JTextField();
        cityField = new javax.swing.JTextField();
        countryField = new javax.swing.JTextField();
        DPHField = new javax.swing.JTextField();
        DICField = new javax.swing.JTextField();
        ICOField = new javax.swing.JTextField();
        IBANField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        telephoneNumberField = new javax.swing.JTextField();
        createCompanyButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create company");
        setMaximumSize(new java.awt.Dimension(611, 510));
        setMinimumSize(new java.awt.Dimension(611, 510));
        setPreferredSize(new java.awt.Dimension(611, 510));
        getContentPane().setLayout(null);

        companyNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                companyNameFieldFocusLost(evt);
            }
        });
        companyNameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                companyNameFieldMouseExited(evt);
            }
        });
        companyNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyNameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(companyNameField);
        companyNameField.setBounds(20, 120, 280, 26);

        ZIPField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ZIPFieldFocusLost(evt);
            }
        });
        getContentPane().add(ZIPField);
        ZIPField.setBounds(20, 220, 280, 26);

        streetField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                streetFieldFocusLost(evt);
            }
        });
        getContentPane().add(streetField);
        streetField.setBounds(20, 170, 280, 26);

        cityField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cityFieldFocusLost(evt);
            }
        });
        getContentPane().add(cityField);
        cityField.setBounds(310, 170, 280, 26);

        countryField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                countryFieldFocusLost(evt);
            }
        });
        getContentPane().add(countryField);
        countryField.setBounds(310, 220, 280, 26);

        DPHField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                DPHFieldFocusLost(evt);
            }
        });
        getContentPane().add(DPHField);
        DPHField.setBounds(20, 340, 280, 26);

        DICField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                DICFieldFocusLost(evt);
            }
        });
        getContentPane().add(DICField);
        DICField.setBounds(310, 280, 280, 26);

        ICOField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ICOFieldFocusLost(evt);
            }
        });
        getContentPane().add(ICOField);
        ICOField.setBounds(20, 280, 280, 26);

        IBANField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                IBANFieldFocusLost(evt);
            }
        });
        getContentPane().add(IBANField);
        IBANField.setBounds(310, 390, 280, 26);

        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFieldFocusLost(evt);
            }
        });
        getContentPane().add(emailField);
        emailField.setBounds(20, 390, 280, 26);

        telephoneNumberField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                telephoneNumberFieldFocusLost(evt);
            }
        });
        getContentPane().add(telephoneNumberField);
        telephoneNumberField.setBounds(310, 340, 280, 26);

        createCompanyButton.setFont(new java.awt.Font("Alegreya", 3, 13)); // NOI18N
        createCompanyButton.setForeground(new java.awt.Color(0, 51, 153));
        createCompanyButton.setText("Create!");
        createCompanyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCompanyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(createCompanyButton);
        createCompanyButton.setBounds(490, 450, 110, 29);

        jLabel5.setFont(new java.awt.Font("Alegreya", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setText("IBAN");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 370, 110, 26);

        jLabel2.setFont(new java.awt.Font("Nickainley", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Create company");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 20, 230, 60);

        jLabel6.setFont(new java.awt.Font("Alegreya", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setText("Company name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 90, 110, 26);

        jLabel7.setFont(new java.awt.Font("Alegreya", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 153));
        jLabel7.setText("Street");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 150, 110, 26);

        jLabel8.setFont(new java.awt.Font("Alegreya", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 153));
        jLabel8.setText("City");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(320, 150, 110, 26);

        jLabel9.setFont(new java.awt.Font("Alegreya", 2, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 153));
        jLabel9.setText("ZIP");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 200, 110, 26);

        jLabel10.setFont(new java.awt.Font("Alegreya", 2, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 153));
        jLabel10.setText("Country");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(320, 200, 110, 26);

        jLabel11.setFont(new java.awt.Font("Alegreya", 2, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 153));
        jLabel11.setText("ICO");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 260, 110, 26);

        jLabel12.setFont(new java.awt.Font("Alegreya", 2, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 153));
        jLabel12.setText("DIC");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(320, 260, 110, 26);

        jLabel13.setFont(new java.awt.Font("Alegreya", 2, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 153));
        jLabel13.setText("ICDPH");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 320, 110, 26);

        jLabel14.setFont(new java.awt.Font("Alegreya", 2, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 153));
        jLabel14.setText("Tel. number");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(320, 320, 110, 26);

        jLabel15.setFont(new java.awt.Font("Alegreya", 2, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 153));
        jLabel15.setText("E-mail");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(30, 370, 110, 26);

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/martinapivarnikova/Downloads/default.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 80, 590, 360);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/martinapivarnikova/Downloads/Large_UL-877.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 610, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createCompanyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCompanyButtonActionPerformed

        if (companyNameField.getText().isEmpty() || streetField.getText().isEmpty()
                || cityField.getText().isEmpty() || ZIPField.getText().isEmpty()
                || countryField.getText().isEmpty()) {
            new BadFilledForm(this, true, "First five fields can not be empty!").setVisible(true);
        } else {
            try {
                Company newOne = new Company();

                newOne.setCompanyName(companyNameField.getText());
                newOne.setStreet(streetField.getText());
                newOne.setCity(cityField.getText());

                if (!ZIPField.getText().isEmpty()) {
                    newOne.setPostalCode(Integer.parseInt(ZIPField.getText()));
                }
                newOne.setCountry(countryField.getText());
                if (!ICOField.getText().isEmpty()) {
                    newOne.setICO(Long.parseLong(ICOField.getText()));
                }
                if (!DICField.getText().isEmpty()) {
                    newOne.setDIC(Long.parseLong(DICField.getText()));
                }
                if (!DPHField.getText().isEmpty()) {
                    newOne.setICDPH(Long.parseLong(DPHField.getText()));
                }
                newOne.setTelephoneNumber(telephoneNumberField.getText());
                newOne.setEmail(emailField.getText());
                newOne.setIBAN(IBANField.getText());

                if (whoIsCreating != null) {

                    if ("supplier".equals(whoIsCreating)) {
                        createInvoiceForm.setSupplier(newOne);
                        createInvoiceForm.setButtonTextChooseSupplier(newOne.getCompanyName());
                        companies.addCompany(newOne);

                    }
                    if ("customer".equals(whoIsCreating)) {
                        createInvoiceForm.setCustomer(newOne);
                        createInvoiceForm.setButtonTextChooseCustomer(newOne.getCompanyName());
                        companies.addCompany(newOne);

                    }
                } else {

                    if (selected != null) {
                        newOne.setId(selected.getId());

                        companies.updateCompany(newOne);

                    } else {
                        companies.addCompany(newOne);
                    }
                }
                this.dispose();
            } catch (NumberFormatException e) {
                new BadFilledForm(this, true, "Repair all red fields").setVisible(true);

            }

        }
    }//GEN-LAST:event_createCompanyButtonActionPerformed

    private void companyNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyNameFieldActionPerformed

    private void companyNameFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companyNameFieldMouseExited

    }//GEN-LAST:event_companyNameFieldMouseExited

    private void companyNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_companyNameFieldFocusLost

     }//GEN-LAST:event_companyNameFieldFocusLost

    private void streetFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_streetFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_streetFieldFocusLost

    private void cityFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cityFieldFocusLost

    private void ZIPFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ZIPFieldFocusLost
        try {
            ZIPField.setForeground(Color.black);

            if (!ZIPField.getText().isEmpty()) {
                Integer.parseInt(ZIPField.getText());
            }
        } catch (NumberFormatException e) {
            ZIPField.setForeground(Color.red);
            new BadFilledForm(this, true, "ZIP must be a number!").setVisible(true);
        }
    }//GEN-LAST:event_ZIPFieldFocusLost

    private void countryFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_countryFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_countryFieldFocusLost

    private void ICOFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ICOFieldFocusLost
        try {
            ICOField.setForeground(Color.black);
            if (!ICOField.getText().isEmpty()) {
                Long.parseLong(ICOField.getText());
            }
        } catch (NumberFormatException e) {
            ICOField.setForeground(Color.red);
            new BadFilledForm(this, true, "ICO must be a number!").setVisible(true);
        }    }//GEN-LAST:event_ICOFieldFocusLost

    private void DICFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DICFieldFocusLost
        try {
            DICField.setForeground(Color.black);

            if (!DICField.getText().isEmpty()) {
                Long.parseLong(DICField.getText());
            }
        } catch (NumberFormatException e) {
            DICField.setForeground(Color.red);
            new BadFilledForm(this, true, "DIC must be a number!").setVisible(true);

        }    }//GEN-LAST:event_DICFieldFocusLost

    private void DPHFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DPHFieldFocusLost
        try {
            DPHField.setForeground(Color.black);

            if (!DPHField.getText().isEmpty()) {
                Long.parseLong(DPHField.getText());
            }
        } catch (NumberFormatException e) {
            DPHField.setForeground(Color.red);
            new BadFilledForm(this, true, "ICDPH must be a number!").setVisible(true);
        }    }//GEN-LAST:event_DPHFieldFocusLost

    private void telephoneNumberFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telephoneNumberFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_telephoneNumberFieldFocusLost

    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldFocusLost

    private void IBANFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IBANFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_IBANFieldFocusLost

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DICField;
    private javax.swing.JTextField DPHField;
    private javax.swing.JTextField IBANField;
    private javax.swing.JTextField ICOField;
    private javax.swing.JTextField ZIPField;
    private javax.swing.JTextField cityField;
    private javax.swing.JTextField companyNameField;
    private javax.swing.JTextField countryField;
    private javax.swing.JButton createCompanyButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField streetField;
    private javax.swing.JTextField telephoneNumberField;
    // End of variables declaration//GEN-END:variables
}
