/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.invoicesystem.forms;

import java.awt.Dialog;
import sk.upjs.invoicesystem.Invoice;
import sk.upjs.invoicesystem.InvoiceTableModel;
import sk.upjs.invoicesystem.InvoicesDao;
import sk.upjs.invoicesystem.ObjectFactory;

/**
 *
 * @author kriza
 */
public class InvoicesForm extends javax.swing.JDialog {

    private InvoicesDao invoicesDAO = ObjectFactory.INSTANCE.getInvoicesDao();

    /**
     * Creates new form InvoicesForm
     */
    public InvoicesForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        setLocationRelativeTo(parent);
        refreshInvoiceForm();
    }

    private void refreshInvoiceForm() {
        InvoiceTableModel model = (InvoiceTableModel) invoiceFormTable.getModel();
        model.refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteInvoiceButton = new javax.swing.JButton();
        createInvoiceButton = new javax.swing.JButton();
        updateInvoiceButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        invoiceFormTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Invoices");
        setBounds(new java.awt.Rectangle(0, 0, 550, 610));
        setMaximumSize(new java.awt.Dimension(550, 610));
        setMinimumSize(new java.awt.Dimension(550, 610));
        setPreferredSize(new java.awt.Dimension(550, 610));
        getContentPane().setLayout(null);

        deleteInvoiceButton.setFont(new java.awt.Font("Alegreya", 3, 18)); // NOI18N
        deleteInvoiceButton.setForeground(new java.awt.Color(0, 51, 153));
        deleteInvoiceButton.setText("Delete invoice");
        deleteInvoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteInvoiceButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteInvoiceButton);
        deleteInvoiceButton.setBounds(170, 90, 140, 40);

        createInvoiceButton.setFont(new java.awt.Font("Alegreya", 3, 18)); // NOI18N
        createInvoiceButton.setForeground(new java.awt.Color(0, 51, 153));
        createInvoiceButton.setText("Create invoice");
        createInvoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createInvoiceButtonActionPerformed(evt);
            }
        });
        getContentPane().add(createInvoiceButton);
        createInvoiceButton.setBounds(390, 90, 137, 40);

        updateInvoiceButton.setFont(new java.awt.Font("Alegreya", 3, 18)); // NOI18N
        updateInvoiceButton.setForeground(new java.awt.Color(0, 51, 153));
        updateInvoiceButton.setText("Update invoice");
        updateInvoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInvoiceButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateInvoiceButton);
        updateInvoiceButton.setBounds(20, 90, 137, 40);

        invoiceFormTable.setModel(new InvoiceTableModel());
        jScrollPane1.setViewportView(invoiceFormTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(17, 140, 510, 410);

        jLabel1.setFont(new java.awt.Font("Nickainley", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Invoices");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 10, 150, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/martinapivarnikova/Downloads/Large_UL-877.jpg")); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(550, 610));
        jLabel2.setMinimumSize(new java.awt.Dimension(550, 610));
        jLabel2.setPreferredSize(new java.awt.Dimension(550, 610));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 550, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createInvoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createInvoiceButtonActionPerformed
        CreateInvoiceForm createInvoicesForm = new CreateInvoiceForm(this, true);
        createInvoicesForm.setVisible(true);
        refreshInvoiceForm();
    }//GEN-LAST:event_createInvoiceButtonActionPerformed

    private void deleteInvoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteInvoiceButtonActionPerformed
        int selectedRow = invoiceFormTable.getSelectedRow();
        if (selectedRow != -1) {
            Invoice selected = invoicesDAO.getInvoices().get(invoiceFormTable.getSelectedRow());
            if (selected != null) {
                invoicesDAO.deleteInvoice(selected);
                refreshInvoiceForm();
            }
        }
    }//GEN-LAST:event_deleteInvoiceButtonActionPerformed

    private void updateInvoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInvoiceButtonActionPerformed
        int selectedRow = invoiceFormTable.getSelectedRow();
        if (selectedRow != -1) {
            CreateInvoiceForm createInvoicesForm = new CreateInvoiceForm(this, true, selectedRow);
            createInvoicesForm.setVisible(true);
            refreshInvoiceForm();
        }
    }//GEN-LAST:event_updateInvoiceButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoicesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoicesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoicesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoicesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new InvoicesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createInvoiceButton;
    private javax.swing.JButton deleteInvoiceButton;
    private javax.swing.JTable invoiceFormTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateInvoiceButton;
    // End of variables declaration//GEN-END:variables
}
